# System Prep
- hosts: all
  sudo: true
  roles:
    - role: rvm_io.rvm1-ruby
      tags: ruby
      sudo: True
      rvm1_install_flags: '--auto-dotfiles --user-install'
      rvm1_install_path: '/home/{{ ansible_ssh_user }}/.rvm'
      rvm1_user: '{{ ansible_ssh_user }}'
    - role: geerlingguy.git
  tasks:
    - name: install js runtime
      apt: name=nodejs update_cache=yes

# Bundle install
- hosts: all
  tasks:
    - name: bundle install
      command: bash -lc "bundle install"
      args:
        chdir: /vagrant

- hosts: all
  tasks:
    - name: set working dir
      shell: 'echo "cd /{{ ansible_ssh_user }}" >> /home/{{ ansible_ssh_user }}/.bashrc'
